<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/10/16 14:19:09
return array(
'search' => new sfRoute('/search/*', array (
  'module' => 'search',
  'action' => 'index',
), array (
), array (
)),
'recentfeed' => new sfRoute('/feed/recent/:format', array (
  'module' => 'feed',
  'action' => 'recent',
  'format' => 'rss201',
), array (
), array (
)),
'download' => new sfRoute('/download/:project/:tag', array (
  'module' => 'default',
  'action' => 'download',
), array (
), array (
)),
'twitterlogin' => new sfRoute('/login/twitter', array (
  'module' => 'user',
  'action' => 'loginTwitter',
), array (
), array (
)),
'login' => new sfRoute('/login', array (
  'module' => 'user',
  'action' => 'login',
), array (
), array (
)),
'pluginguidelines' => new sfRoute('/plugin-guidelines', array (
  'module' => 'pages',
  'action' => 'guidelines',
), array (
), array (
)),
'developers' => new sfRoute('/developers/*', array (
  'module' => 'developers',
), array (
), array (
)),
'howtoadd' => new sfRoute('/how-to-add', array (
  'module' => 'pages',
  'action' => 'howToAdd',
), array (
), array (
)),
'settings' => new sfRoute('/settings', array (
  'module' => 'user',
  'action' => 'edit',
), array (
), array (
)),
'logout' => new sfRoute('/logout', array (
  'module' => 'user',
  'action' => 'logout',
), array (
), array (
)),
'add' => new sfRoute('/add', array (
  'module' => 'plugin',
  'action' => 'add',
), array (
), array (
)),
'add-2' => new sfRoute('/add-2', array (
  'module' => 'plugin',
  'action' => 'add2',
), array (
), array (
)),
'add-3' => new sfRoute('/add-3', array (
  'module' => 'plugin',
  'action' => 'add3',
), array (
), array (
)),
'add-4' => new sfRoute('/add-4', array (
  'module' => 'plugin',
  'action' => 'add4',
), array (
), array (
)),
'add-5' => new sfRoute('/add-5', array (
  'module' => 'plugin',
  'action' => 'add5',
), array (
), array (
)),
'add-6' => new sfRoute('/add-6', array (
  'module' => 'plugin',
  'action' => 'add6',
), array (
), array (
)),
'user' => new sfRoute('/profile/:username', array (
  'module' => 'user',
  'action' => 'view',
), array (
), array (
)),
'pluginupdate' => new sfRoute('/p/:slug/update/*', array (
  'module' => 'plugin',
  'action' => 'update',
), array (
), array (
)),
'plugindiscuss' => new sfRoute('/p/:slug/discuss/*', array (
  'module' => 'plugin',
  'action' => 'discuss',
), array (
), array (
)),
'plugin' => new sfRoute('/p/:slug/*', array (
  'module' => 'plugin',
  'action' => 'view',
), array (
), array (
)),
'signup' => new sfRoute('/signup', array (
  'module' => 'user',
  'action' => 'signup',
), array (
), array (
)),
'forgot' => new sfRoute('/login/forgot', array (
  'module' => 'user',
  'action' => 'forgot',
), array (
), array (
)),
'browse' => new sfRoute('/browse/*', array (
  'module' => 'browse',
  'action' => 'filter',
), array (
), array (
)),
'twitter' => new sfRoute('/twitter', array (
  'module' => 'user',
  'action' => 'index',
), array (
), array (
)),
'homepage' => new sfRoute('/', array (
  'module' => 'default',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
