<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/10/16 14:19:06
sfConfig::add(array(
  'app_gravatar_default_size' => 48,
  'app_gravatar_default_rating' => 'G',
  'app_gravatar_default_image' => 'gravatar-48.png',
  'app_gravatar_cache_dir_name' => 'avatars',
  'app_gravatar_cache_expiration' => '3 days',
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => true,
  'library' => 'GD_MIME_Type',
),
  'app_title_prefix' => 'MooTools Plugins |',
  'app_webmaster_email' => 'forge@mootools.net',
  'app_screenshots_path' => 'screenshots',
  'app_screenshots_width' => 120,
  'app_screenshots_height' => 85,
  'app_screenshots_primarywidth' => 185,
  'app_screenshots_primaryheight' => 78,
  'app_git_storage_path' => '/Users/willy/Sites/Personal/MooForge/git/',
  'app_git_command' => '/opt/local/bin/git',
  'app_plugin_dev_loose_mode' => true,
  'app_browse_per_page' => 10,
  'app_twitter_consumer_key' => 'FrPf98reevKh2BGKzqRoA',
  'app_twitter_consumer_secret' => 'LiIKnnribXNt2VHXHXbAnZpeo0gtDVnA2gsSFSrWPsw',
));
