<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/10/16 14:19:08

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:dbname=mooforge;host=localhost',
  'username' => 'root',
  'password' => 1234,
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
