<?php
// auto-generated by sfViewConfigHandler
// date: 2009/10/16 14:23:29
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'MooTools Plugins', false, false);
  $response->addMeta('description', 'Directory of MooTools plugins contributed by the community.', false, false);
  $response->addMeta('keywords', 'mootools plugins, javascript plugins, mootools addons, mootools ui, mootools widgets, widgets, addons, plugins', false, false);
  $response->addMeta('language', 'en', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('forge.css', '', array ());
  $response->addJavascript('mootools-1.2.2-core+more.js', '', array ());
  $response->addJavascript('lighter.js', '', array ());
  $response->addJavascript('forge.js', '', array ());


