<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/10/16 14:23:29
$this->security = array (
  'edit' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
